
# ------------------------------
# Namespace (already exists for you, but safe to keep)
# ------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
---
# ------------------------------
# Rollout (Blue-Green strategy, auto-promotion)
# ------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-demo
  namespace: argo-rollouts
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: bluegreen-demo
  template:
    metadata:
      labels:
        app: bluegreen-demo
    spec:
      containers:
      - name: app
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 2
          periodSeconds: 5
  strategy:
    blueGreen:
      activeService: bluegreen-active
      previewService: bluegreen-preview
      autoPromotionEnabled: true      # ← changed from false → true
      previewReplicaCount: 1
      scaleDownDelaySeconds: 30
---
# ------------------------------
# Active Service (ClusterIP)
# ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-active
  namespace: argo-rollouts
spec:
  selector:
    app: bluegreen-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
# ------------------------------
# Preview Service (ClusterIP)
# ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-preview
  namespace: argo-rollouts
spec:
  selector:
    app: bluegreen-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080

